apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pmem-csi-sc-ephemeral
provisioner: pmem-csi
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  persistencyType: ephemeral
