apiVersion: v1
kind: ServiceAccount
metadata:
  name: pmem-csi-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: pmem-csi-operator
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  - services/finalizers
  - serviceaccounts
  - endpoints
  - events
  - secrets
  - pods
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - daemonsets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - apps
  resourceNames:
  - pmem-csi-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pmem-csi-operator
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - pmem-csi.intel.com
  resources:
  - deployments
  - deployments/status
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pmem-csi-operator
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pmem-csi-operator
subjects:
- kind: ServiceAccount
  name: pmem-csi-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pmem-csi-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pmem-csi-operator
subjects:
- kind: ServiceAccount
  name: pmem-csi-operator
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmem-csi-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pmem-csi-operator
  template:
    metadata:
      labels:
        app: pmem-csi-operator
        name: pmem-csi-operator
        pmem-csi.intel.com/webhook: ignore
    spec:
      containers:
      - command:
        - /usr/local/bin/pmem-csi-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: pmem-csi-operator
        image: intel/pmem-csi-operator:canary
        imagePullPolicy: IfNotPresent
        name: pmem-csi-operator
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      serviceAccountName: pmem-csi-operator
      volumes:
      - emptyDir: {}
        name: tmp
