bases:
- ../operator

resources:
- webhook-certificate.yaml
- webhook-service.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: pmem-csi-operator
  path: ../patches/operator-webhook-patch.yaml

vars:
- name: SERVICE_NAME
  objref:
    apiVersion: v1
    kind: Service
    name: pmem-csi-operator-service
  fieldref:
    fieldpath: metadata.name
- name: SERVICE_NAMESPACE
  objref:
    apiVersion: v1
    kind: Service
    name: pmem-csi-operator-service
  fieldref:
    fieldpath: metadata.namespace

configurations:
- kustomizeconfig.yaml