apiVersion: v1
kind: Service
metadata:
  name: pmem-csi-operator-service # name referenced in webhook-certificate.yaml for dnsNames
  namespace: default
spec:
  ports:
    - port: 9443
      targetPort: 9443
  selector:
    name: pmem-csi-operator